# Generated by Django 5.1.4 on 2024-12-17 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_payment_razorpay_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Alexandria', 'Alexandria'), ('Aswan', 'Aswan'), ('Asyut', 'Asyut'), ('Beheira', 'Beheira'), ('Beni Suef', 'Beni Suef'), ('Cairo', 'Cairo'), ('Dakahlia', 'Dakahlia'), ('Damietta', 'Damietta'), ('Faiyum', 'Faiyum'), ('Gharbia', 'Gharbia'), ('Giza', 'Giza'), ('Ismailia', 'Ismailia'), ('Kafr El Sheikh', 'Kafr El Sheikh'), ('Luxor', 'Luxor'), ('Matruh', 'Matruh'), ('Minya', 'Minya'), ('Monufia', 'Monufia'), ('New Valley', 'New Valley'), ('North Sinai', 'North Sinai'), ('Port Said', 'Port Said'), ('Qalyubia', 'Qalyubia'), ('Qena', 'Qena'), ('Red Sea', 'Red Sea'), ('Sharqia', 'Sharqia'), ('Sohag', 'Sohag'), ('South Sinai', 'South Sinai'), ('Suez', 'Suez')], max_length=100),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
