# Generated by Django 5.1.4 on 2024-12-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_customer_state_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('holder', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=70)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('ticket_number', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
                ('card_number', models.CharField(max_length=20)),
                ('expiration_month', models.CharField(max_length=10)),
                ('expiration_year', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=10)),
            ],
        ),
    ]
