# Generated by Django 5.1.4 on 2024-12-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='paypal_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_status',
        ),
    ]
